// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZGcZMCgh4HLt2lz_eoBUwpZ5Bv7yCDZc',
    appId: '1:295185290409:web:f536499eb3c9309e09c5b8',
    messagingSenderId: '295185290409',
    projectId: 'bmcsports-1e831',
    authDomain: 'bmcsports-1e831.firebaseapp.com',
    storageBucket: 'bmcsports-1e831.firebasestorage.app',
    measurementId: 'G-67G4YHYVWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwbP6ZlO_JCxtdEr7lZkE-a0OqJdb1GS8',
    appId: '1:295185290409:android:aee7b9e8ddfc70cc09c5b8',
    messagingSenderId: '295185290409',
    projectId: 'bmcsports-1e831',
    storageBucket: 'bmcsports-1e831.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTNGnONcwd8y7qaKN-1fHkfdShLGARAy4',
    appId: '1:295185290409:ios:ec8f6c85b04723ff09c5b8',
    messagingSenderId: '295185290409',
    projectId: 'bmcsports-1e831',
    storageBucket: 'bmcsports-1e831.firebasestorage.app',
    iosBundleId: 'com.example.bmcsports',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZGcZMCgh4HLt2lz_eoBUwpZ5Bv7yCDZc',
    appId: '1:295185290409:web:a4b0f12eca65dad209c5b8',
    messagingSenderId: '295185290409',
    projectId: 'bmcsports-1e831',
    authDomain: 'bmcsports-1e831.firebaseapp.com',
    storageBucket: 'bmcsports-1e831.firebasestorage.app',
    measurementId: 'G-9HGRDT3L8N',
  );
}
